### ISSUE TITLE
出现报错

### ISSUE THREAD

**Issue by 123654mjx** [yz1639/FscanOutputBeautify#2]
![image](https://github.com/yz1639/FscanOutputBeautify/assets/107984618/92fed230-dadd-46e6-8eb9-c7024225dab0)

**Comment by yz1639** [comment]
用的是1.0.4吗？fscan是什么版本，方便提供一份脱敏源文件吗

**Comment by 123654mjx** [comment]
加个v私聊吗? 1.0.4和一开始的版本报错一样，fscan是1.8.2

**Comment by 123654mjx** [comment]
加个v私聊吗?

**Comment by yz1639** [comment]
你发吧，我加您

**Comment by 123654mjx** [comment]
![e3a09d3a232b7e01f33fc9e889b9dd8](https://github.com/yz1639/FscanOutputBeautify/assets/107984618/2b65acd0-0460-4e87-853b-01643cf05f21)

**Comment by yz1639** [comment]
已添加

**Comment by daymissed** [comment]
今天测试一下跟楼主报的错是一样的。

**Comment by daymissed** [comment]
![image](https://github.com/yz1639/FscanOutputBeautify/assets/62062283/11ad35e6-ff36-4775-87e6-686671b03911)

**Comment by yz1639** [comment]
v1.0.6已修复此问题
