### ISSUE TITLE
还是报错

### ISSUE THREAD

**Issue by daymissed** [yz1639/FscanOutputBeautify#3]
fscan版本：1.8.3 
![image](https://github.com/yz1639/FscanOutputBeautify/assets/62062283/cdd9ddd1-af68-425d-bf30-0a445dc1cf24)

**Comment by yz1639** [comment]
你用的1.0.5吗

**Comment by daymissed** [comment]
是的，刚下载的

**Comment by yz1639** [comment]
方便提供一份脱敏源文件吗

**Comment by daymissed** [comment]
怎么发给你

**Comment by yz1639** [comment]
你打开https://bashupload.com, 上传上去 将链接发我

**Comment by daymissed** [comment]
https://bashupload.com/NZkJk/test.txt

**Comment by yz1639** [comment]
师傅, 方便您用1.8.2再扫一次吗, 我发现了一些其他bug 需要对照下1.8.2的结果

**Comment by daymissed** [comment]
晚点来测试一下，谢谢

**Comment by yz1639** [comment]
师傅试试 1.0.6

**Comment by daymissed** [comment]
大佬太牛B了,1.0.6版本完美
